@Dierentuin42_HostAddress = https://localhost:7003




GET {{Dierentuin42_HostAddress}}/api/animals

###

GET {{Dierentuin42_HostAddress}}/api/animals/id

###

GET {{Dierentuin42_HostAddress}}/api/animals/search?name=Nicholas&species=Kangoeroe&category=Gorczany&size=Small&diet=Herbivore&activity=Nocturnal&prey=Towels&enclosure=Glenna&security=Low

###

POST {{Dierentuin42_HostAddress}}/api/animals
Content-Type: application/json

{
  "name": "test", 
  "species": "testspecies", 
  "categoryId": 1481,  
  "animalSize": 2, 
  "animalDiet": 2, 
  "animalActivityPattern": 1, 
  "prey": "testprey", 
  "enclosureId": 1497,
  "spaceRequirement": 345.76,
  "securityRequirement": 1 

}

###

PUT {{Dierentuin42_HostAddress}}/api/animals/id
Content-Type: application/json

{
  "id": int id,
  "name": "testveranderen", 
  "species": "testspecies", 
  "categoryId": 1481,  
  "animalSize": 2, 
  "animalDiet": 2, 
  "animalActivityPattern": 1, 
  "prey": "testprey", 
  "enclosureId": 1497,
  "spaceRequirement": 345.76,
  "securityRequirement": 1 
}

###

DELETE {{Dierentuin42_HostAddress}}/api/animals/id

###

GET {{Dierentuin42_HostAddress}}/api/categories

###

GET {{Dierentuin42_HostAddress}}/api/categories/id

###

GET {{Dierentuin42_HostAddress}}/api/categories/search?name=string

###

POST {{Dierentuin42_HostAddress}}/api/categories
Content-Type: application/json

{
    "name": "testcategorie",
    "animals":
    [
      {
      "name": "test", 
      "species": "testspecies", 
      "animalSize": 2, 
      "animalDiet": 2, 
      "animalActivityPattern": 1, 
      "prey": "testprey", 
      "spaceRequirement": 345.76,
      "securityRequirement": 1 
      },
      {
      "name": "test2", 
      "species": "testspecies2", 
      "animalSize": 2, 
      "animalDiet": 2, 
      "animalActivityPattern": 1, 
      "prey": "testprey", 
      "spaceRequirement": 345.76,
      "securityRequirement": 1 
      }
    ]
}

###

PUT {{Dierentuin42_HostAddress}}/api/categories/1482
Content-Type: application/json

{
    "id":  1482,
    "name": "testcategorieveranderen",
    "animals":
    [
      {
      "name": "test", 
      "species": "testspeciesveranderen", 
      "animalSize": 2, 
      "animalDiet": 2, 
      "animalActivityPattern": 1, 
      "prey": "testprey", 
      "spaceRequirement": 345.76,
      "securityRequirement": 1 
      },
      {
      "name": "test2", 
      "species": "testspecies2veranderen", 
      "animalSize": 2, 
      "animalDiet": 2, 
      "animalActivityPattern": 1, 
      "prey": "testprey", 
      "spaceRequirement": 345.76,
      "securityRequirement": 1 
      }
    ]
}

###

DELETE {{Dierentuin42_HostAddress}}/api/categories/id

###

GET {{Dierentuin42_HostAddress}}/api/enclosures

###

GET {{Dierentuin42_HostAddress}}/api/enclosures/id

###

GET {{Dierentuin42_HostAddress}}/api/enclosures/search?name=Greyson&zoo=Lessie&climate=Temperate&habitat=Grassland&security=Medium&space=8494.12

###

POST {{Dierentuin42_HostAddress}}/api/enclosures
Content-Type: application/json

{
    "name": "test",
    "zooId": 891,
    "animals": [],
    "enclosureClimate": 1,
    "enclosureHabitatType": 2,
    "enclosureSecurityLevel": 1,
    "size": 2000
}

###

PUT {{Dierentuin42_HostAddress}}/api/enclosures/1503
Content-Type: application/json

{
    "id": 1503,
    "name": "testveranderen",
    "zooId": 891,
    "animals": [],
    "enclosureClimate": 1,
    "enclosureHabitatType": 2,
    "enclosureSecurityLevel": 1,
    "size": 2002
}

###

DELETE {{Dierentuin42_HostAddress}}/api/enclosures/1503

###

GET {{Dierentuin42_HostAddress}}/api/zoos

###

GET {{Dierentuin42_HostAddress}}/api/zoos/id

###

GET {{Dierentuin42_HostAddress}}/api/zoos/search?name=string

###

POST {{Dierentuin42_HostAddress}}/api/zoos
Content-Type: application/json
{
  "name": "test",
  "enclosures": [
    {
      "name": "test",
      "zooId": 137,
      "zoo": null,
      "animals": [],
      "enclosureClimate": 1,
      "enclosureHabitatType": 3,
      "enclosureSecurityLevel": 1,
      "size": 4000.51
    },
    {
      "name": "test2",
      "zooId": 137,
      "zoo": null,
      "animals": [],
      "enclosureClimate": 2,
      "enclosureHabitatType": 4,
      "enclosureSecurityLevel": 2,
      "size": 3000.51
    }
  ]
}


###

PUT {{Dierentuin42_HostAddress}}/api/zoos/894
Content-Type: application/json

{
  "id": 894,
  "name": "testveranderen",
  "enclosures": [
    {
      "name": "test",
      "zooId": 137,
      "zoo": null,
      "animals": [],
      "enclosureClimate": 1,
      "enclosureHabitatType": 3,
      "enclosureSecurityLevel": 1,
      "size": 4000.51
    },
    {
      "name": "test2",
      "zooId": 137,
      "zoo": null,
      "animals": [],
      "enclosureClimate": 2,
      "enclosureHabitatType": 4,
      "enclosureSecurityLevel": 2,
      "size": 3000.51
    }
  ]
}

###

DELETE {{Dierentuin42_HostAddress}}/api/zoos/id

###
